name: Docker Image CI

on:
  push:
    branches:
      - master  # Build sur chaque push sur la branche master
    tags:
      - '*.*'  # Pousser l'image vers Docker Hub uniquement si un tag de type v<major>.<minor> est poussé

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        # Vérification du tag
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        else
          TAG="latest"  # Si pas de tag, utiliser "latest"
        fi
        docker build . --file Dockerfile --tag alterway/pelican:${TAG}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image to Docker Hub
      if: startsWith(github.ref, 'refs/tags/')  # Ne pousse l'image que si un tag est poussé
      run: docker push alterway/pelican:${TAG}
